export const WATER_SHALLOW_COLOR = 0x527d75;
export const WATER_DEEP_COLOR = 0x0b2a34;
export const WATER_FOAM_COLOR = 0xddebea;
export const WATER_REFLECTION_COLOR = 0x607c89;
export const WATER_HORIZON_REFLECTION_COLOR = 0x91a5aa;
export const WATER_BANK_REFLECTION_COLOR = 0x303e38;
export const WATER_SUN_REFLECTION_COLOR = 0xffc98d;

export const FLOWING_RIVER_SHALLOW_COLOR = 0x61776c;
export const FLOWING_RIVER_DEEP_COLOR = 0x172f39;
export const FLOWING_RIVER_FOAM_COLOR = 0xd7e1dc;
export const FLOWING_RIVER_SEDIMENT_COLOR = 0x858575;
